name: Specmore Demo Catalogue
description: A demo catalogue of interface specification openly available on the internet.
spec-files: 
- file-path: specs/movie-ratings.yaml
- repo: OAI/OpenAPI-Specification
  file-path: examples/v3.0/petstore-expanded.yaml